name: CI

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your Node.js version

      - name: Install server dependencies
        run: |
          cd server
          npm install

      - name: Run server tests and generate coverage
        run: |
          cd server
          npm test -- --coverage

      - name: Install client dependencies
        run: |
          cd client
          npm install

      - name: Run client tests and generate coverage
        run: |
          cd client
          npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Use the secret token
          files: |
            server/coverage/lcov.info
            client/coverage/lcov.info
          fail_ci_if_error: true
